### ISSUE TITLE
Add log out option on profile page

### ISSUE THREAD

**Issue by guytepper** [guytepper/1km.co.il#78]

**Comment by joeyede** [comment]
User should be able to disconnect from site to revert to to anonymous state  
Behavior:
- Disconnect button should appear on top left of all windows
-[optional] If you aren't connected there could be connect button
Clicking disconnect button makes user no longer connected via facebook so that if they want to edit a page they need to connect.

**Comment by guytepper** [comment]
For beginning I'd say put it on the profile page & on the mobile navigation bar (both doesn't exist at the moment)
